AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a S3 bucket that serves its content as a static web site
Parameters:
  Org:
    Type: String
  Project:
    Type: String
  Stage:
    Type: String
Resources:
  WebAppS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ORG}-${PROJECT}-${STAGE}-web
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebAppS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Sub ${ORG}-${PROJECT}-${STAGE}-web
      PolicyDocument:
        Statement:
          - Sid: AllowPublicRead
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebAppS3Bucket
                - /*
Outputs:
  URL:
    Description: URL for the website served from the newly-created bucket
    Value: !GetAtt 
      - WebAppS3Bucket
      - WebsiteURL
  Bucket:
    Description: The bucket that holds the static website
    Value: !Ref WebAppS3Bucket
