aws:
  account: 028568048704
  role: bgmMicroserviceRole
  region: us-east-1
  albumTable: albuminfo
  trackTable: trackinfo

bandcamp:
  bcApiUrl: http://api.bandcamp.com/api
  bcDiscographyPath: /band/3/discography
  bcAlbumPath: /album/2/info
  bcTrackPath: /track/3/info
  bcBandIDs:
    - 230945364

albums:
  forwardSorted:
    - 3708688148 # Songs from the Gleebleverse

badges:
  defaultAlbumIDs:
    - 3708688148 # Songs from the Gleebleverse
    - 3541981135 # Every Song in the Universe
    - 1047117555 # Also this Other Stuff
  badges:
    k:
      code: k
      enum: Karaoke
    p:
      code: p
      enum: Patreon
    j:
      code: j
      enum: JoCoCruise
    s:
      code: s
      enum: Spintunes
    w:
      code: w
      enum: SafeForWork
