bandcamp:
  bcApiUrl: http://api.bandcamp.com/api
  bcDiscographyPath: /band/3/discography
  bcAlbumPath: /album/2/info
  bcTrackPath: /track/3/info
  bcBandIDs:
    - 230945364

badges:
  defaultAlbumIDs:
    - 3541981135
    - 1047117555
  badges:
    p:
      code: p
      enum: Patreon
    s:
      code: s
      enum: Spintunes
    j:
      code: j
      enum: JoCoCruise
    k:
      code: k
      enum: Karaoke
    w:
      code: w
      enum: SafeForWork
