aws:
  account: 028568048704
  region: us-east-1
  sns:
    refreshDiscographyCache:
      topic: RefreshDiscographyCache
      arn: arn:aws:sns:us-east-1:028568048704:RefreshDiscographyCache

bandcamp:
  bcApiUrl: http://api.bandcamp.com/api
  bcDiscographyPath: /band/3/discography
  bcAlbumPath: /album/2/info
  bcTrackPath: /track/3/info
  bcBandIDs:
    - 230945364

badges:
  defaultAlbumIDs:
    - 3708688148
    - 3541981135
    - 1047117555
  badges:
    k:
      code: k
      enum: Karaoke
    p:
      code: p
      enum: Patreon
    j:
      code: j
      enum: JoCoCruise
    s:
      code: s
      enum: Spintunes
    w:
      code: w
      enum: SafeForWork
