AWSTemplateFormatVersion: '2010-09-09'
Description: Test creating a S3 bucket from a GH Action
Resources:
  WebAppS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bgm-nerdrock-gh-actions-test
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebAppS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebAppS3Bucket
      # PolicyDocument:
      #   Version: 2012-10-17
      #   Statement:
      #     - Effect: Allow
      #       Principal: '*'
      #       Action:
      #         - s3:GetObject
      #       Resource: !Join
      #         - ''
      #         - - 'arn:aws:s3:::'
      #           - !Ref WebAppS3Bucket
      #           - /*
