AWSTemplateFormatVersion: '2010-09-09'
Description: Create a resource group for resources deployed in this stack
Parameters:
  Org:
    Type: String
  Project:
    Type: String
  Stage:
    Type: String
Resources:
  ResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ${Org}-${Project}-resources-${Stage}
      Description: !Sub All ${Stage} resources in the ${Project} project
      Tags:
        - Key: project
          Value: !Sub ${Project}
        - Key: STAGE
          Value: !Sub ${Stage}
