AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a lambda function
Parameters:
  Org:
    Type: String
  Project:
    Type: String
  Stage:
    Type: String
  LambdaName:
    Type: String
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/${Org}-${Project}-${Stage}-${LambdaName}
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub ${Org}-${Project}-${Stage}-deploy
        S3Key: !Sub ${Org}-${Project}-${Stage}.zip
      Handler: !Sub handlers.handle_${LambdaName}
      Runtime: python3.12
      FunctionName: !Sub ${Org}-${Project}-${Stage}-${LambdaName}
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          stackName: !Sub ${Org}-${Project}-${Stage}
          config: config.yml
          secretsBucket: !Sub ${Org}-${Project}-${Stage}-secrets
          secretsFile: secrets.yml
          log_level: DEBUG
      Role: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/${Org}MicroserviceRole
    DependsOn:
      - LogGroup
