AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a lambda function
Parameters:
  Org:
    Type: String
  Project:
    Type: String
  Stage:
    Type: String
  LambdaName:
    Type: String
Resources:
  ${LambdaName}LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/${Org}-${Project}-${Stage}-${LambdaName}
  ${LambdaName}LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: ${Org}-${Project}-${Stage}-deploy
        S3Key: ${Org}-${Project}-${Stage}.zip
      Handler: handlers.handle_${LambdaName}
      Runtime: python3.12
      FunctionName: ${Org}-${Project}-${Stage}-${LambdaName}
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          stackName: ${Org}-${Project}-${Stage}
          config: config.yml
          secretsBucket: ${Org}-${Project}-${Stage}-secrets
          secretsFile: secrets.yml
          log_level: DEBUG
      Role: arn:aws:iam::028568048704:role/service-role/${Org}MicroserviceRole
    DependsOn:
      - ${LambdaName}LogGroup
