!CdkConfig
context: !CdkContext
  org: bgm
  project: nerdrock
  domain: briangraymusic.com
  blog_hostname: blog
  blog_target_domain: bgraymusic.github.io
  secrets_file: secrets.yml
  check_ip_url: http://checkip.amazonaws.com
  allow_ip_key: allow_ip
  assets_dir: assets
  non_prod_func_source_file: non_prod_viewer_request_func.js
  prod_func_source_file: prod_viewer_request_func.js

ssm_parameters: !CdkSsmParameters
  prod_deployment_colors: [BLUE, GREEN]
  active_prod_color: BLUE
  secrets_bucket: bgm-nerdrock-global-secrets-bucket

key_value_pairs: !CdkKeyValuePairs
  allowed_ip: 68.80.249.63
  redirect_domain: briangraymusic.com
