AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'

Description: Nerdrock Website Deployment Configuration

Parameters:
  Org:
    Type: String
  Project:
    Type: String
  Stage:
    Type: String

Resources:

  AlbumInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Org}-${Project}-${Stage}-albuminfo
      AttributeDefinitions:
        - AttributeName: album_id
          AttributeType: 'N'
      KeySchema:
        - AttributeName: album_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TrackInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Org}-${Project}-${Stage}-trackinfo
      AttributeDefinitions:
        - AttributeName: album_id
          AttributeType: 'N'
        - AttributeName: number
          AttributeType: 'N'
      KeySchema:
        - AttributeName: album_id
          KeyType: HASH
        - AttributeName: number
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  'Fn::ForEach::Lambdas':
    - LambdaName
    - [badges, discography, refreshDatabase]
    - '${LambdaName}Lambda':
        Type: bgm::nerdrock::lambda::MODULE
        Properties:
          Org: !Sub ${Org}
          Project: !Sub ${Project}
          Stage: !Sub ${Stage}
          LambdaName: !Sub ${LambdaName}

  NerdrockWebsite:
    Type: bgm::nerdrock::s3website::MODULE
    Properties:
      Org: !Sub ${Org}
      Project: !Sub ${Project}
      Stage: !Sub ${Stage}

  NerdrockRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${Org}-${Project}-${Stage}

  NerdrockResourceApi:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt NerdrockRestApi.RootResourceId
      PathPart: api
      RestApiId: !Ref NerdrockRestApi

  ApiGatewayResourceApiBadges:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref NerdrockResourceApi
      PathPart: badges
      RestApiId: !Ref NerdrockRestApi

  ResourceGroup:
    Type: bgm::nerdrock::resourcegroup::MODULE
    Properties:
      Org: !Sub ${Org}
      Project: !Sub ${Project}
      Stage: !Sub ${Stage}
