AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::LanguageExtensions

Description: Nerdrock Website Deployment Configuration

Parameters:
  Org:
    Type: String
  Project:
    Type: String
  Stage:
    Type: String

Resources:

  AlbumInfoTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${Org}-${Project}-${Stage}-albuminfo
      AttributeDefinitions:
        - AttributeName: album_id
          AttributeType: 'N'
      KeySchema:
        - AttributeName: album_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TrackInfoTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${Org}-${Project}-${Stage}-trackinfo
      AttributeDefinitions:
        - AttributeName: album_id
          AttributeType: 'N'
        - AttributeName: number
          AttributeType: 'N'
      KeySchema:
        - AttributeName: album_id
          KeyType: HASH
        - AttributeName: number
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${Org}-${Project}-${Stage}

  RootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: api
      RestApiId: !Ref RestApi

  BadgesLambda:
      Type: bgm::nerdrock::lambda::MODULE
      Properties:
        Org: !Ref Org
        Project: !Ref Project
        Stage: !Ref Stage
        LambdaName: badges

  DiscographyLambda:
      Type: bgm::nerdrock::lambda::MODULE
      Properties:
        Org: !Ref Org
        Project: !Ref Project
        Stage: !Ref Stage
        LambdaName: discography

  RefreshDatabaseLambda:
      Type: bgm::nerdrock::lambda::MODULE
      Properties:
        Org: !Ref Org
        Project: !Ref Project
        Stage: !Ref Stage
        LambdaName: refreshDatabase

  NerdrockWebsite:
    Type: bgm::nerdrock::s3website::MODULE
    Properties:
      Org: !Sub ${Org}
      Project: !Sub ${Project}
      Stage: !Sub ${Stage}

  ResourceGroup:
    Type: bgm::nerdrock::resourcegroup::MODULE
    Properties:
      Org: !Sub ${Org}
      Project: !Sub ${Project}
      Stage: !Sub ${Stage}
