AWSTemplateFormatVersion: '2010-09-09'
Description: Test creating a S3 bucket from a GH Action
Parameters:
  Org:
    Type: String
  Project:
    Type: String
  Stage:
    Type: String
  BucketName:
    Type: String
Resources:
  NerdrockWebsite:
    Type: bgm::nerdrock::s3website::MODULE
    Properties:
      BucketName: !Sub ${BucketName}
  # WebAppS3Bucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub ${BucketName}
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: false
  #       BlockPublicPolicy: false
  #       IgnorePublicAcls: false
  #       RestrictPublicBuckets: false
  #     WebsiteConfiguration:
  #       IndexDocument: index.html
  #       ErrorDocument: error.html
  # WebAppS3BucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Sub ${BucketName}
  #     PolicyDocument:
  #       Statement:
  #         - Sid: AllowPublicRead
  #           Effect: Allow
  #           Principal:
  #             AWS: '*'
  #           Action:
  #             - s3:GetObject
  #           Resource: !Join
  #             - ''
  #             - - 'arn:aws:s3:::'
  #               - !Ref WebAppS3Bucket
  #               - /*
  ResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ${Org}-${Project}-resources-${Stage}
      Description: !Sub All ${Stage} resources in the ${Project} project
      Tags:
        - Key: project
          Value: !Sub ${Project}
        - Key: STAGE
          Value: !Sub ${Stage}
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - WebAppS3Bucket
      - WebsiteURL
    Description: URL for website served from the ${BucketName} bucket
