AWSTemplateFormatVersion: '2010-09-09'
Description: Nerdrock Website Deployment Configuration
Parameters:
  Org:
    Type: String
  Project:
    Type: String
  Stage:
    Type: String
Resources:
  NerdrockWebsite:
    Type: bgm::nerdrock::s3website::MODULE
    Properties:
      Org: !Sub ${Org}
      Project: !Sub ${Project}
      Stage: !Sub ${Stage}
  ResourceGroup:
    Type: bgm::nerdrock::resourcegroup::MODULE
    Properties:
      Org: !Sub ${Org}
      Project: !Sub ${Project}
      Stage: !Sub ${Stage}
