AWSTemplateFormatVersion: '2010-09-09'
Description: Test creating a S3 bucket from a GH Action
Parameters:
  Org:
    Type: String
  Project:
    Type: String
  Stage:
    Type: String
  BucketName:
    Type: String
Resources:
  NerdrockWebsite:
    Type: bgm::nerdrock::s3website::MODULE
    Properties:
      BucketName: !Sub ${BucketName}
  ResourceGroup:
    Type: bgm::nerdrock::resourcegroup::MODULE
    Properties:
      Org: !Sub ${Org}
      Project: !Sub ${Project}
      Stage: !Sub ${Stage}
