AWSTemplateFormatVersion: '2010-09-09'
Description: Test creating a S3 bucket from a GH Action
Parameters:
  Org:
    Type: String
  Project:
    Type: String
  Stage:
    Type: String
  BucketName:
    Type: String
Resources:
  NerdrockWebsite:
    Type: bgm::nerdrock::s3website::MODULE
    Properties:
      BucketName: !Sub ${BucketName}
  ResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ${Org}-${Project}-resources-${Stage}
      Description: !Sub All ${Stage} resources in the ${Project} project
      Tags:
        - Key: project
          Value: !Sub ${Project}
        - Key: STAGE
          Value: !Sub ${Stage}
