aws:
  account: '028568048704'
  role: bgmMicroserviceRole
  region: us-east-1
  album_table: albuminfo
  track_table: trackinfo

bandcamp:
  bc_api_url: https://api.bandcamp.com/api
  bc_discography_path: /band/3/discography
  bc_album_path: /album/2/info
  bc_track_path: /track/3/info
  bc_band_ids:
    - 230945364

albums:
  forward_sorted:
    - 3708688148 # Songs from the Gleebleverse

badges:
  default_album_ids:
    - 3708688148 # Songs from the Gleebleverse
    - 3541981135 # Every Song Ever
    - 1047117555 # Also this Other Stuff
  badges:
    k:
      code: k
      enum: Karaoke
    p:
      code: p
      enum: Patreon
    j:
      code: j
      enum: JoCoCruise
    s:
      code: s
      enum: Spintunes
    w:
      code: w
      enum: SafeForWork
