name: Deploy Nerdrock (experimental)

on:
  workflow_dispatch
  # push:
  #   branches:
  #   - main

env:
  ORG: bgm
  PROJECT: nerdrock
  STAGE: experimental

jobs:
  prepare-modules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout IaC Directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        sparse-checkout: |
          iac

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Python Modules
      run: python -m pip install --upgrade boto3

    - name: Get List of Modules to Submit
      id: module-finder
      run: python3 -u iac/deploy-modules.py getModulesToSubmit

    - name: Install cfn
      if: ${{ steps.module-finder.outputs.MODULES_TO_SUBMIT }} != '[]'
      run: pip install --upgrade cloudformation-cli

    - name: Submit Modules
      if: ${{ steps.module-finder.outputs.MODULES_TO_SUBMIT }} != '[]'
      run: python3 -u iac/deploy-modules.py submitModules '${{ steps.module-finder.outputs.MODULES_TO_SUBMIT }}'

  deploy:
    runs-on: ubuntu-latest
    needs: prepare-modules

    steps:
    - name: Checkout Web Directory
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          iac
          web

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy project
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ env.ORG }}-${{ env.PROJECT }}-${{ env.STAGE }}
        template: ./iac/create-${{ env.PROJECT }}.template.yml
        no-fail-on-empty-changeset: "1"
        capabilities: >-
          CAPABILITY_AUTO_EXPAND
        tags: >-
          [
            {"Key":"project","Value":"${{ env.PROJECT }}"},
            {"Key":"STAGE","Value":"${{ env.STAGE }}"}
          ]
        parameter-overrides: >-
          Org=${{ env.ORG }},
          Project=${{ env.PROJECT }},
          Stage=${{ env.STAGE }},
          BucketName=${{ env.ORG }}-${{ env.PROJECT }}-${{ env.STAGE }}-web

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./web/ s3://${{ env.ORG }}-${{ env.PROJECT }}-${{ env.STAGE }}-web --delete --exclude serve
