name: On Dev Branch Created or Changed

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch in which to simulate change"
        required: true
        type: string
  push:
    branches-ignore: [trunk]
    paths-ignore: [.github/**]

defaults:
  run:
    shell: bash -v {0}

jobs:
  deploy-nerdrock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.ref_name }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Nerdrock CLI
        run: pip install '.[cli]'

      - name: Deploy
        run: bgnr -t -v deploy -e ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.ref_name }}
