name: On Branch Deleted

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch in which to simulate deletion'
        required: true
        type: string
  delete: # does not support filtering by type (branch), must do later

defaults:
  run:
    shell: bash -v {0}

env:
  DEBUG: true

jobs:
  undeploy-nerdrock:
    runs-on: ubuntu-latest

    # delete can be branches or tags; we want only branches
    if: github.ref_type == 'branch' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Dump Context
        if: env.DEBUG
        run: |
          echo "${{ toJson(github) }}"

      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Nerdrock CLI
        run: pip install '.[cli]'

      - name: Undeploy
        run: bgnr -t -v undeploy -e ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.event.ref }}
