name: On Release Created

on: create # does not support filtering by type (tag), must do later

defaults:
  run:
    shell: bash -v {0}

jobs:
  deploy-to-prod:
    if: github.event.ref_type == 'tag' # create can be branches or tags; we want only tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Nerdrock CLI
        run: pip install '.[cli]'

      - name: Deploy
        run: bgnr -t -v deploy -e prod
