name: Deploy Web Site to S3

on:
	push:
		branches:
  		- main

jobs:
	deploy:
		runs-on: ubuntu-latest
		steps:
		- name: checkout
			uses: actions/checkout@v1
		- run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
		- name: List files in the repository
			run: |
				ls ${{ github.workspace }}
