name: Deploy Web Site to S3

on: workflow_dispatch
  # push:
  #   branches:
  #   - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Web Directory
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          web

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create S3 bucket
      run: echo "Create S3 bucket TBD"

    - name: Deploy static site to S3 bucket
      run: echo "Deploy web site to S3 bucket TBD"
