name: Deploy Web Site to S3

on:
  workflow_dispatch
  # push:
  #   branches:
  #   - main

env:
  ORG: bgm
  PROJECT: nerdrock
  STAGE: experimental
  STACK: ${{ env.ORG }}-${{ env.PROJECT }}-${{ env.STAGE }}
  BUCKET_NAME: ${{ env.ORG }}-${{ env.PROJECT }}-${{ env.STAGE }}-web

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Web Directory
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          web

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create S3 bucket
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ env.STACK }}
        template: ./create-s3-bucket.template.yml
        no-fail-on-empty-changeset: "1"
        tags: '[{"Key":"project","Value":"${{ env.PROJECT }}"},{"Key":"STAGE","Value":"${{ env.STAGE }}"}]'
        parameter-overrides: BucketName=${{ env.BUCKET_NAME }}

    - name: Create ResourceGroup
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ env.STACK }}
        template: ./create-resource-group.template.yml
        no-fail-on-empty-changeset: "1"
        tags: '[{"Key":"project","Value":"${{ env.PROJECT }}"},{"Key":"STAGE","Value":"${{ env.STAGE }}"}]'
        parameter-overrides: Org=${{ env.ORG }},Project=${{ env.PROJECT }},Stage=${{ env.STAGE }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./web/ s3://${{ env.BUCKET_NAME }} --delete --exclude serve
